services:
  db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system
      POSTGRES_DB: weather_data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql

    networks:
      - my_network

    
  af:
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - 8087:8080
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
     
    volumes:
       - ./airflow/dags:/opt/airflow/dags
       - ./api_request:/opt/airflow/api_request
       - ./dbt:/opt/airflow/dbt        # âœ… ADD THIS
       - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - db
    networks:
      - my_network
    command: airflow standalone
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:latest

    volumes:
      - ./dbt/my_project:/usr/app
      - ./dbt:/root/.dbt
      - ./dbt:/opt/airflow/dbt  
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
      
    depends_on:
      - db
    networks:
      - my_network
    # command: init my_project
    command: debug
    # command : run

  

  

 
networks:
  my_network:
    driver: bridge
    

