services:
  db:
    container_name: postgres_db
    image: postgres:18
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system
      POSTGRES_DB: weather_data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
