services:
  db:
    container_name: postgres_db
    image: postgres:16
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: system
      POSTGRES_DB: weather_data
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network
    
  af:
    container_name: airflow_container
    image: apache/airflow:latest
    ports:
      - 8087:8080
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
     
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api_request:/opt/airflow/api_request
    depends_on:
      - db
    networks:
      - my_network
    command: airflow standalone
 
networks:
  my_network:
    driver: bridge
    

